[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
providers = ["node", "java"]

[build]
cmd = """
npm install
npx tailwindcss -i ./src/main/resources/static/css/input.css -o ./src/main/resources/static/css/output.css --minify
./mvnw clean package -DskipTests
"""

[deploy]
startCommand = "java -jar target/*.jar"
